### ISSUE TITLE
Playnite 10 support?

### ISSUE THREAD

**Issue by wilco375** [felixkmh/DuplicateHider#125]
I am new to Playnite and have version 10.20 installed. I installed your addon, but duplicate games have not disappeared in my library. Is v10 not supported, or is there some action I need to perform after installing the addon to combine the duplicates? See some examples below:
![image](https://github.com/felixkmh/DuplicateHider/assets/7385023/ad96ca00-f3d9-4293-ab8a-5e3b545065bc)
![image](https://github.com/felixkmh/DuplicateHider/assets/7385023/eee10d75-3c0a-4241-b760-23ce963ced3b)
![image](https://github.com/felixkmh/DuplicateHider/assets/7385023/b24a498b-7f7f-4302-8f50-d1eb51954f6d)

**Comment by felixkmh** [comment]
By default, hiding duplicates has to be triggered manually. This is so that you can configure it before actually hiding anything.
So you can trigger it manually using the main menu: https://github.com/felixkmh/DuplicateHider#extension-menu
You can also enabled the option to automatically hide/reveal duplicates under the common options tab in the Add-ons settings section for DuplicateHider.

**Comment by wilco375** [comment]
> By default, hiding duplicates has to be triggered manually. This is so that you can configure it before actually hiding anything. So you can trigger it manually using the main menu: [felixkmh/DuplicateHider#extension-menu](https://github.com/felixkmh/DuplicateHider#extension-menu) You can also enabled the option to automatically hide/reveal duplicates under the common options tab in the Add-ons settings section for DuplicateHider.

Thanks for the clarification, I missed that part of the readme
