### ISSUE TITLE
UI integration seems to max out at 4 copies

### ISSUE THREAD

**Issue by erys** [felixkmh/DuplicateHider#33]
I've somehow ended up with a game with five copies, but only 4 icons/versions show up in the ui integration in the details list. This was true for DH_Night, Harmony, and eMixedNite, so I'm assuming it's an issue with DuplicateHider rather than the specific themes.

Screenshots from DH_Night

Detail list shows 4 icons
![2021-11-01 17_03_11-Playnite](https://user-images.githubusercontent.com/12535744/139742198-8668bac3-2013-45d3-b7f6-e9849b4d05cd.png)
But there are 5 copies (amazon is the one missing from the icons in the details list, which is the lowest priority)
![2021-11-01 17_03_49-Playnite](https://user-images.githubusercontent.com/12535744/139742200-2dcd84ab-ee73-43f4-8639-390d59734618.png)
This was most noticeable with eMixedNite which has the icons in the game detail view as well as the detail list:
![2021-11-01 17_12_31-Playnite](https://user-images.githubusercontent.com/12535744/139743063-7fd3aafb-6c03-4f9d-bda2-849c39f54855.png)

**Comment by felixkmh** [comment]
This is intentional. Theme creators can spedify the maximum number of icons for each view. If this value is not set, it defaults to 4. Hence the behaviour that you are describing. I wanted to prevent the UI integration from breaking layouts due to too many icons, so I left it up to the theme creators.

For DH_Night for example, you can change that value using the ThemeModifier extension.

Another way too get more icons is to add the following constants to a themes ```Constants.xaml``` file:
```
<sys:Int32 x:Key="DuplicateHider_MaxNumberOfIcons">4</sys:Int32>
<sys:Int32 x:Key="DuplicateHider_MaxNumberOfIcons1">8</sys:Int32>
<sys:Int32 x:Key="DuplicateHider_MaxNumberOfIcons2">8</sys:Int32>
```
You can then change those values as you like, 0 meaning no limit to the number of icons. Just be careful when adding them. If some of them are already there, duplicating constants will probably prevent the theme from loading at all.
