### ISSUE TITLE
Playnite crash when launching game

### ISSUE THREAD

**Issue by Mellified** [felixkmh/DuplicateHider#79]
When launching a game from StartPage I'm intermittently seeing Duplicate Hider cause Playnite to crash. No idea why launching a game involves Duplicate Hider at all!
[DupeHider_Crash.zip](https://github.com/felixkmh/DuplicateHider/files/8840169/DupeHider_Crash.zip)
[DupeHider_Crash_2.zip](https://github.com/felixkmh/DuplicateHider/files/8840171/DupeHider_Crash_2.zip)

**Comment by felixkmh** [comment]
Launching a game does trigger an event that a game has changed, which DH needs to react to, because it could affect game priorities, depending on the priority setup. Try if it still happens with this:
[felixkmh_DuplicateHider_Plugin_3_10_7.zip](https://github.com/felixkmh/DuplicateHider/files/8840619/felixkmh_DuplicateHider_Plugin_3_10_7.zip)

**Comment by Mellified** [comment]
The problem isn't 100% consistent. I haven't been able to re-create it yet though.

**Comment by felixkmh** [comment]
Sounds good to me
